Repository Sysone-1/.98, pull requests merged in 2025-07, with the labels that each got.

#17 [Feature/#15 calendar] 달력 생성
  .idea/.name
  .idea/vcs.xml
  .java-version
  build.gradle.kts
  libs/view-11.12.7.jar
  src/main/java/com/sysone/ogamza/Main.java
  src/main/java/com/sysone/ogamza/controller/UserHomeController.java
  src/main/java/com/sysone/ogamza/controller/user/DashboardController.java
  src/main/java/com/sysone/ogamza/controller/user/MainController.java
  src/main/java/com/sysone/ogamza/controller/user/NFCController.java
  src/main/java/com/sysone/ogamza/controller/user/RecordController.java
  src/main/java/com/sysone/ogamza/controller/user/UserHomeController.java
  src/main/java/com/sysone/ogamza/view/Header.java
  src/main/java/com/sysone/ogamza/view/MainLayout.java
  src/main/java/com/sysone/ogamza/view/SideBar.java
  src/main/java/com/sysone/ogamza/view/user/CalendarView.java
  src/main/resources/fxml/NFCTest.fxml
  src/main/resources/fxml/user/Dashboard.fxml
  src/main/resources/fxml/user/Record.fxml
  src/main/resources/fxml/user/UserHome.fxml
  src/main/resources/fxml/user/UserMainLayout.fxml
Labels: enhancement

#31 [Feature/#26 ranking] 랭킹 시스템, gpt 연결
  .idea/misc.xml
  build.gradle.kts
  libs/view-11.12.7.jar
  src/main/java/com/sysone/ogamza/controller/user/UserHomeController.java
  src/main/java/com/sysone/ogamza/dao/user/RankingDAO.java
  src/main/java/com/sysone/ogamza/dao/user/UserHomeDAO.java
  src/main/java/com/sysone/ogamza/dto/user/RankingDTO.java
  src/main/java/com/sysone/ogamza/dto/user/TodayFortuneDTO.java
  src/main/java/com/sysone/ogamza/dto/user/UserInfoDTO.java
  src/main/java/com/sysone/ogamza/service/user/FortuneService.java
  src/main/java/com/sysone/ogamza/service/user/UserHomeService.java
  src/main/java/com/sysone/ogamza/sql/user/UserHomeSQL.java
  src/main/java/com/sysone/ogamza/utils/api/GPTService.java
  src/main/java/com/sysone/ogamza/utils/api/GptPrompt.java
  src/main/java/com/sysone/ogamza/utils/db/DbTest.java
  src/main/resources/fxml/user/UserHome.fxml
Labels: enhancement

#37 Feature/#4 nfc function
  .idea/encodings.xml
  src/main/java/com/sysone/ogamza/controller/admin/AdminRecordController.java
  src/main/java/com/sysone/ogamza/controller/user/DashboardController.java
  src/main/java/com/sysone/ogamza/controller/user/MainController.java
  src/main/java/com/sysone/ogamza/controller/user/NFCCardTagController.java
  src/main/java/com/sysone/ogamza/controller/user/NFCController.java
  src/main/java/com/sysone/ogamza/controller/user/NFCRegisterController.java
  src/main/java/com/sysone/ogamza/dao/user/NFCDAO.java
  src/main/java/com/sysone/ogamza/dto/user/DepartmentDTO.java
  src/main/java/com/sysone/ogamza/dto/user/EmployeeCreateDTO.java
  src/main/java/com/sysone/ogamza/service/user/DashboardService.java
  src/main/java/com/sysone/ogamza/service/user/NFCService.java
  src/main/java/com/sysone/ogamza/sql/user/NFCSql.java
  src/main/resources/fxml/user/Dashboard.fxml
  src/main/resources/fxml/user/EmployeeRegister.fxml
  src/main/resources/fxml/user/EmployeeTag.fxml
  src/main/resources/fxml/user/NFCTest.fxml
  src/main/resources/fxml/user/ScheduleRegister.fxml
  src/main/resources/fxml/user/UserMainLayout.fxml
  src/main/resources/images/fail.jpg
  src/main/resources/images/fdfdfdfdf.jpg
Labels: enhancement

#35 [Feature/#19 adminHome] 관리자 화면 기능 구현
  .idea/.name
  .idea/encodings.xml
  build.gradle.kts
  src/main/java/com/sysone/ogamza/controller/admin/AdminHomeController.java
  src/main/java/com/sysone/ogamza/controller/admin/AdminMainController.java
  src/main/java/com/sysone/ogamza/controller/admin/CompletedRequestListController.java
  src/main/java/com/sysone/ogamza/controller/admin/RequestListController.java
  src/main/java/com/sysone/ogamza/controller/user/DashboardController.java
  src/main/java/com/sysone/ogamza/controller/user/MainController.java
  src/main/java/com/sysone/ogamza/dao/admin/AttendanceStatsDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/ClockChangeRequestDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/OutworkRequestDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/RequestDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/ScheduleRequestDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/VacationRequestDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/WorkDeviationDAO.java
  src/main/java/com/sysone/ogamza/dto/admin/BaseRequestDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/ClockChangeRequestDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/OutworkRequestDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/VacationRequestDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/WorkDeviationModelDTO.java
  src/main/java/com/sysone/ogamza/enums/RequestType.java
  src/main/java/com/sysone/ogamza/service/admin/AttendanceStatsService.java
  src/main/java/com/sysone/ogamza/service/admin/RequestService.java
  src/main/java/com/sysone/ogamza/service/admin/WorkDeviationService.java
  src/main/java/com/sysone/ogamza/utils/db/DbTest.java
  src/main/java/com/sysone/ogamza/utils/db/OracleConnector.java
  src/main/resources/fxml/admin/AdminHome.fxml
  src/main/resources/fxml/admin/AdminMainLayout.fxml
  src/main/resources/fxml/admin/CompleteRequestList.fxml
  src/main/resources/fxml/admin/RequestList.fxml
Labels: enhancement

#39 [Feature/#32 record] 유저 출퇴근 기록, 전역 헤더 수정
  build.gradle.kts
  src/main/java/com/sysone/ogamza/LoginController.java
  src/main/java/com/sysone/ogamza/LoginDAO.java
  src/main/java/com/sysone/ogamza/LoginUserDTO.java
  src/main/java/com/sysone/ogamza/Main.java
  src/main/java/com/sysone/ogamza/controller/user/DashboardController.java
  src/main/java/com/sysone/ogamza/controller/user/MainController.java
  src/main/java/com/sysone/ogamza/controller/user/RecordController.java
  src/main/java/com/sysone/ogamza/controller/user/UserHomeController.java
  src/main/java/com/sysone/ogamza/dao/user/UserRecordDAO.java
  src/main/java/com/sysone/ogamza/dto/user/UserRecordDTO.java
  src/main/java/com/sysone/ogamza/sql/user/UserRecordSQL.java
  src/main/resources/css/main.css
  src/main/resources/fxml/Login.fxml
  src/main/resources/fxml/user/Record.fxml
  src/main/resources/fxml/user/UserHome.fxml
  src/main/resources/fxml/user/UserMainLayout.fxml
Labels: enhancement

#45 [Feature/#24 AdminDashboardPage] 관리자 대시보드 페이지 구현
  src/main/java/com/sysone/ogamza/controller/admin/AdminDashboardController.java
  src/main/java/com/sysone/ogamza/controller/admin/AdminMainController.java
  src/main/java/com/sysone/ogamza/controller/admin/ChartGroupController.java
  src/main/java/com/sysone/ogamza/dao/admin/DashboardDAO.java
  src/main/java/com/sysone/ogamza/dto/admin/AttendanceStatusDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/OvertimeData.java
  src/main/java/com/sysone/ogamza/service/admin/AdminDashboardService.java
  src/main/resources/fxml/admin/AdminDashboard.fxml
  src/main/resources/fxml/admin/ChartGroup.fxml
Labels: enhancement

#43 [Feature/#40 message receiver] 쪽지 수신 시스템, userHome 마름모 수정
  .idea/misc.xml
  src/main/java/com/sysone/ogamza/controller/user/MainController.java
  src/main/java/com/sysone/ogamza/controller/user/MessageDetailController.java
  src/main/java/com/sysone/ogamza/controller/user/MessageInBoxController.java
  src/main/java/com/sysone/ogamza/controller/user/UserHomeController.java
  src/main/java/com/sysone/ogamza/controller/user/WriteMessageController.java
  src/main/java/com/sysone/ogamza/dao/user/MessageReceiverDAO.java
  src/main/java/com/sysone/ogamza/dto/user/MessageBoxViewDTO.java
  src/main/java/com/sysone/ogamza/dto/user/MessageDetailDTO.java
  src/main/java/com/sysone/ogamza/dto/user/MessageInBoxDTO.java
  src/main/java/com/sysone/ogamza/dto/user/MessageSentBoxDTO.java
  src/main/java/com/sysone/ogamza/service/user/MessageService.java
  src/main/java/com/sysone/ogamza/sql/user/MessageReceiverSQL.java
  src/main/java/com/sysone/ogamza/view/user/MessageBoxCell.java
  src/main/java/com/sysone/ogamza/view/user/UserShape.java
  src/main/resources/fxml/user/MessageDetail.fxml
  src/main/resources/fxml/user/MessageInBox.fxml
  src/main/resources/fxml/user/UserMainLayout.fxml
  src/main/resources/fxml/user/WriteMessage.fxml
  src/main/resources/images/bogum.png
  src/main/resources/images/quotes_14662021.gif
  src/main/resources/images/writing.gif
Labels: enhancement

#51 [Feature/#46 CommonAdminFeature] 관리자 헤더 공통 기능 구현
  src/main/java/com/sysone/ogamza/controller/admin/AdminMainController.java
  src/main/java/com/sysone/ogamza/controller/admin/UnauthorizedAccessLogController.java
  src/main/java/com/sysone/ogamza/dao/admin/NotificationDAO.java
  src/main/java/com/sysone/ogamza/service/admin/NotificationService.java
  src/main/java/com/sysone/ogamza/sql/admin/NotificationSql.java
  src/main/java/com/sysone/ogamza/utils/db/OracleConnector.java
  src/main/resources/fxml/admin/AdminMainLayout.fxml
  src/main/resources/fxml/admin/UnauthorizedAccessLogDialog.fxml
  src/main/resources/images/notification.png
  src/main/resources/images/profile/taeyong.png
Labels: enhancement

#54 [style/#5 userDashboard] 유저 대시보드 UI 변경 (레이아웃, 일정 리스트)
  src/main/java/com/sysone/ogamza/controller/user/DashboardController.java
  src/main/java/com/sysone/ogamza/controller/user/ScheduleListController.java
  src/main/java/com/sysone/ogamza/service/user/DashboardService.java
  src/main/java/com/sysone/ogamza/sql/user/DashboardSql.java
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/user/Dashboard.fxml
  src/main/resources/fxml/user/ScheduleContent.fxml
  src/main/resources/fxml/user/ScheduleList.fxml
Labels: enhancement

#59 [Refactor/#58 AdminRefactoring] 관리자 코드 주석 추가
  src/main/java/com/sysone/ogamza/controller/admin/AdminDashboardController.java
  src/main/java/com/sysone/ogamza/controller/admin/AdminMainController.java
  src/main/java/com/sysone/ogamza/controller/admin/AdminRecordController.java
  src/main/java/com/sysone/ogamza/controller/admin/ChartGroupController.java
  src/main/java/com/sysone/ogamza/controller/admin/UnauthorizedAccessLogController.java
  src/main/java/com/sysone/ogamza/dao/admin/DashboardDAO.java
  src/main/java/com/sysone/ogamza/dao/admin/NotificationDAO.java
  src/main/java/com/sysone/ogamza/dto/admin/AttendanceStatusDTO.java
  src/main/java/com/sysone/ogamza/dto/admin/OvertimeData.java
  src/main/java/com/sysone/ogamza/service/admin/AdminDashboardService.java
  src/main/java/com/sysone/ogamza/service/admin/NotificationService.java
  src/main/java/com/sysone/ogamza/utils/db/OracleConnector.java
  src/main/resources/fxml/admin/AdminDashboard.fxml
  src/main/resources/fxml/admin/AdminMainLayout.fxml
  src/main/resources/fxml/admin/AdminRecord.fxml
  src/main/resources/fxml/admin/ChartGroup.fxml
  src/main/resources/fxml/admin/UnauthorizedAccessLogDialog.fxml
Labels: documentation

#76 [fix AdminDashboard] 관리자 대시보드 콤보박스 수정
  src/main/java/com/sysone/ogamza/controller/admin/ChartGroupController.java
Labels: bug
